trigger:
- main  # alebo master, záleží od názvu vašej hlavnej vetvy

pool:
  vmImage: 'macos-latest'  # Použitie macOS ako hostovanej agentúry

variables:
  buildConfiguration: 'Release'
  reportDirectory: '$(System.DefaultWorkingDirectory)/test_report'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.x'  # Verzia .NET SDK (zodpovedá vášmu projektu)
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    mkdir -p "$(reportDirectory)"
  displayName: 'Create test_report directory'

- script: |
    dotnet build --configuration $(buildConfiguration)
  displayName: 'Build Project'

- script: |
    # Priama inštalácia prehliadačov prostredníctvom PowerShell skriptu
    cd $(System.DefaultWorkingDirectory)
    dotnet build -t:Restore
    cd bin/$(buildConfiguration)/net9.0
    dotnet new tool-manifest || true
    dotnet tool install --local Microsoft.Playwright.CLI
    dotnet tool run playwright install --with-deps chromium
  displayName: 'Install Playwright Browsers'

- script: |
    # Diagnostika obsahu adresárov
    echo "Checking bin directory"
    ls -la $(System.DefaultWorkingDirectory)/bin/$(buildConfiguration)/net9.0
    echo "Checking Playwright installation"
    find $(System.DefaultWorkingDirectory) -name ".playwright" -type d | xargs ls -la 2>/dev/null || echo "No .playwright directory found"
    find $(System.DefaultWorkingDirectory) -path "*/.playwright/*" -name "chromium*" 2>/dev/null || echo "No chromium found"
  displayName: 'Check Playwright Installation'

- script: |
    dotnet test --configuration $(buildConfiguration) --logger trx
  displayName: 'Run Tests'
  env:
    PLAYWRIGHT_BROWSERS_PATH: '0'  # Používaj štandardnú cestu
    REPORT_DIRECTORY: '$(reportDirectory)'

- task: PublishTestResults@2
  displayName: 'Publish test results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: false
    testRunTitle: 'Playwright Tests'

- task: PublishBuildArtifacts@1
  displayName: 'Publish test reports'
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: '$(reportDirectory)'
    ArtifactName: 'test-results'
    publishLocation: 'Container'
