trigger:
- main  # alebo master, záleží od názvu vašej hlavnej vetvy

pool:
  vmImage: 'macos-latest'  # Použitie macOS ako hostovanej agentúry

variables:
  buildConfiguration: 'Release'
  reportDirectory: '$(System.DefaultWorkingDirectory)/test_report'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.x'  # Verzia .NET SDK (zodpovedá vášmu projektu)
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    mkdir -p "$(reportDirectory)"
  displayName: 'Create test_report directory'

- script: |
    dotnet build --configuration $(buildConfiguration)
  displayName: 'Build Project'

- script: |
    # Nainštaluj Playwright prehliadače pomocou MSBuild
    dotnet build --target=AddPlaywrightBrowsers -p:PlaywrightBrowser="all"
  displayName: 'Install Playwright Browsers'

- script: |
    # Výpis adresárovej štruktúry pre potreby diagnostiky
    echo "Checking Playwright Browsers installation"
    ls -la $(System.DefaultWorkingDirectory)/bin/$(buildConfiguration)/net9.0 || echo "Directory not found"
    find $(System.DefaultWorkingDirectory) -name "playwright" -type d
    find $(System.DefaultWorkingDirectory) -name ".playwright" -type d
  displayName: 'Check Playwright Installation'

- script: |
    dotnet test --configuration $(buildConfiguration) --logger trx
  displayName: 'Run Tests'
  env:
    PLAYWRIGHT_BROWSERS_PATH: '0'  # Používaj štandardnú cestu
    REPORT_DIRECTORY: '$(reportDirectory)'

- task: PublishTestResults@2
  displayName: 'Publish test results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: false
    testRunTitle: 'Playwright Tests'

- task: PublishBuildArtifacts@1
  displayName: 'Publish test reports'
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: '$(reportDirectory)'
    ArtifactName: 'test-results'
    publishLocation: 'Container'
