# Odstránená sekcia trigger
# trigger:
# - main  # alebo master, záleží od názvu vašej hlavnej vetvy

schedules:
- cron: "0 9 * * 5"  # Spustí sa každý piatok o 9:00
  displayName: 'Weekly Friday Build'
  branches:
    include:
    - test1  # alebo iná vetva, ktorú chcete spúšťať

pool:
  vmImage: 'macos-latest'  # Použitie macOS ako hostovanej agentúry

variables:
  buildConfiguration: 'Release'
  reportDirectory: '$(System.DefaultWorkingDirectory)/test_report'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.x'  # Verzia .NET SDK (zodpovedá vášmu projektu)
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    mkdir -p "$(reportDirectory)"
  displayName: 'Create test_report directory'

- script: |
    dotnet build --configuration $(buildConfiguration)
  displayName: 'Build Project'

- script: |
    # Zjednodušený prístup - priama manipulácia so súbormi
    cd $(System.DefaultWorkingDirectory)
    
    # Nainštalovať Playwright bez MS Build
    PLAYWRIGHT_BROWSERS_PATH=$(System.DefaultWorkingDirectory)/.playwright
    echo "Setting PLAYWRIGHT_BROWSERS_PATH=$PLAYWRIGHT_BROWSERS_PATH"
    mkdir -p $PLAYWRIGHT_BROWSERS_PATH
    
    # Nainštaluj Playwright CLI 
    dotnet tool install --global Microsoft.Playwright.CLI

    # Nainštaluj prehliadače do definovaného adresára
    PLAYWRIGHT_BROWSERS_PATH=$PLAYWRIGHT_BROWSERS_PATH playwright install chromium
    
    # Vypíš obsah nainštalovaného adresára
    echo "Installed Playwright browsers at $PLAYWRIGHT_BROWSERS_PATH:"
    ls -la $PLAYWRIGHT_BROWSERS_PATH
    ls -la $PLAYWRIGHT_BROWSERS_PATH/*
  displayName: 'Install Playwright Browsers'

#test 1
- script: |
    echo "PLAYWRIGHT_BROWSERS_PATH=$(System.DefaultWorkingDirectory)/.playwright" >> $GITHUB_ENV
    find $(System.DefaultWorkingDirectory)/.playwright -type d
    dotnet test --configuration $(buildConfiguration) --logger trx --filter "FullyQualifiedName=PowerAppsLoginTests.Test_PowerAppsLogin"
  displayName: 'Run Test: UPR_IT_NewRequest' #change name of test
  env:
    PLAYWRIGHT_BROWSERS_PATH: "$(System.DefaultWorkingDirectory)/.playwright"
    REPORT_DIRECTORY: '$(reportDirectory)'

#test2
- script: |
    echo "PLAYWRIGHT_BROWSERS_PATH=$(System.DefaultWorkingDirectory)/.playwright" >> $GITHUB_ENV
    find $(System.DefaultWorkingDirectory)/.playwright -type d
    dotnet test --configuration $(buildConfiguration) --logger trx --filter "FullyQualifiedName=PowerAppsLoginCreateStudent.Test_PowerAppsCreateStudent"
  displayName: 'Run Test: UPR_Drilling_VE_NewRequest' #change name of test
  env:
    PLAYWRIGHT_BROWSERS_PATH: "$(System.DefaultWorkingDirectory)/.playwright"
    REPORT_DIRECTORY: '$(reportDirectory)'

#test3
- script: |
    echo "PLAYWRIGHT_BROWSERS_PATH=$(System.DefaultWorkingDirectory)/.playwright" >> $GITHUB_ENV
    find $(System.DefaultWorkingDirectory)/.playwright -type d
    dotnet test --configuration $(buildConfiguration) --logger trx --filter "FullyQualifiedName=PowerAppsLoginCreateStudentInvalidPhone.Test_PowerAppsCreateStudentInvalidPhone"
  displayName: 'Run Test: UPR_Drilling_VENAS_NewRequest' #change name of test
  env:
    PLAYWRIGHT_BROWSERS_PATH: "$(System.DefaultWorkingDirectory)/.playwright"
    REPORT_DIRECTORY: '$(reportDirectory)'

- task: PublishTestResults@2
  displayName: 'Publish test results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: false
    testRunTitle: 'Playwright Tests'

- task: PublishBuildArtifacts@1
  displayName: 'Publish test reports'
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: '$(reportDirectory)'
    ArtifactName: 'test-results'
    publishLocation: 'Container'
